### ISSUE TITLE
Support for Ploen 5.2 and Python 3?

### ISSUE THREAD

**Issue by htgoebel** [4teamwork/ftw.blog#50]
Does this add-on support Plone 5.2 and Python 3? As far as I can see, this is not the case. What are the plans?

**Comment by jone** [comment]
At the moment we do not have plans to update `ftw.blog` to Plone 5 or Python 3.
This package is still using Archetypes; a reimplementation with Dexterity would be necessary on order to update to Plone 5 / Python 3.

You might want to take a look at [ftw.news](https://github.com/4teamwork/ftw.news), which has some similarities and is built on top of [ftw.simplelayout](https://github.com/4teamwork/ftw.simplelayout) and has Plone 5 support. But we did not yet start on Python 3 support; that will take a while.
